version: '3.5'
services:
  database:
    container_name: postgress
    image: postgres
    volumes:
      - db-data:/var/lib/postgres/data
    env_file: database.conf
    ports:
      - 5432:5432
  rabbitmq3:
        container_name: "rabbitmq"
        image: rabbitmq:3.8-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=sarna
            - RABBITMQ_DEFAULT_PASS=sarna
        ports:
            # AMQP protocol port
            - '5672:5672'
            # HTTP management UI
            - '15672:15672'
  stockapiworker:
    build: stockapiworker
    volumes:
      - stockapiworker:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - database
      - rabbitmq3
    restart: always
  predictionworker:
    build: predictionworker
    volumes:
      - predictionworker:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - database
      - rabbitmq3
    restart: always
volumes:
  db-data:
  predictionworker:
  stockapiworker: